import type { MetadataRoute } from 'next';

/**
 * Installable: "Add to Home Screen" opens the site full-screen with Kiru as
 * its icon, like an app. Icons are generated by scripts/make-icons.mjs.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Smart Disruptions',
    short_name: 'Smart Disruptions',
    description:
      'Honest breakdowns of things I build with AI — the timeline, the method, and the parts worth copying.',
    start_url: '/',
    scope: '/',
    display: 'standalone',
    orientation: 'portrait',
    background_color: '#090b16',
    theme_color: '#090b16',
    categories: ['education', 'technology', 'productivity'],
    icons: [
      { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/icons/maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
    shortcuts: [
      { name: 'Writing', url: '/content', icons: [{ src: '/icons/icon-192.png', sizes: '192x192' }] },
      { name: 'Market Storm', url: '/market-storm', icons: [{ src: '/icons/icon-192.png', sizes: '192x192' }] },
      { name: 'Arcade', url: '/games', icons: [{ src: '/icons/icon-192.png', sizes: '192x192' }] },
    ],
  };
}
