import type { LevelId, LevelMeta } from '../types';

/**
 * The six levels: everything but their objects. The song for each level is
 * composed to `sections`, and the level is built to the same sections, so a
 * mode change lands on a section change and the busy parts land on the loud
 * parts. Bars are 4 beats. Durations: First Light 60.0 s · Lantern Row 69.7 s
 * · Moon Gate 72.7 s · Storm Roofs 75.4 s · Dragon Festival 76.8 s · Shadow
 * Dojo 84.0 s.
 *
 * One new way to move per level, Geometry Dash style: Run and Kite, then
 * spirit lanterns, then gravity and Roll, then Parasol and speed, then Dragon
 * and Shadow Step, then everything.
 */
export const LEVEL_METAS: LevelMeta[] = [
  {
    id: 'first-light',
    n: 1,
    name: 'First Light',
    tagline: 'Dawn on the rooftops. Learn to jump, then to fly.',
    difficulty: 'easy',
    stars: 2,
    bpm: 112,
    theme: 'dawn',
    startMode: 'run',
    startSpeed: 'normal',
    modes: ['run', 'kite'],
    sections: [
      {
        name: 'intro',
        bars: 4,
        energy: 1,
        mode: 'run',
        speed: 'normal',
        note: 'Find your feet. A sign says tap to jump; a few single spikes, far apart.',
      },
      {
        name: 'a',
        bars: 8,
        energy: 2,
        mode: 'run',
        speed: 'normal',
        note: 'Single and double spikes, the first rooftop gap, a one-block step up.',
      },
      {
        name: 'b',
        bars: 8,
        energy: 3,
        mode: 'run',
        speed: 'normal',
        note: 'Blocks to land on, the first yellow drum, the first triple spike.',
      },
      {
        name: 'c',
        bars: 6,
        energy: 3,
        mode: 'kite',
        speed: 'normal',
        note: 'The first Kite gate: a wide, gentle corridor over the roofs.',
      },
      {
        name: 'outro',
        bars: 2,
        energy: 1,
        mode: 'run',
        speed: 'normal',
        note: 'Land and run it home.',
      },
    ],
  },
  {
    id: 'lantern-row',
    n: 2,
    name: 'Lantern Row',
    tagline: 'Kick off the spirit lanterns down festival street.',
    difficulty: 'normal',
    stars: 3,
    bpm: 124,
    theme: 'lanterns',
    startMode: 'run',
    startSpeed: 'normal',
    modes: ['run', 'kite'],
    sections: [
      {
        name: 'intro',
        bars: 4,
        energy: 1,
        mode: 'run',
        speed: 'normal',
        note: 'The festival street opens. A sign: tap in mid-air on a lantern.',
      },
      {
        name: 'a',
        bars: 8,
        energy: 2,
        mode: 'run',
        speed: 'normal',
        note: 'Yellow spirit lanterns: jump off them over gaps and spike pits.',
      },
      {
        name: 'b',
        bars: 8,
        energy: 3,
        mode: 'kite',
        speed: 'normal',
        note: 'Kite between lantern strings and past the crows.',
      },
      {
        name: 'c',
        bars: 8,
        energy: 4,
        mode: 'run',
        speed: 'normal',
        note: 'Pink and red lanterns, drums into lanterns, short chains.',
      },
      {
        name: 'd',
        bars: 6,
        energy: 4,
        mode: 'run',
        speed: 'fast',
        note: 'Wind chevrons: the fast section.',
      },
      {
        name: 'outro',
        bars: 2,
        energy: 1,
        mode: 'run',
        speed: 'fast',
        note: 'Run home under the lanterns.',
      },
    ],
  },
  {
    id: 'moon-gate',
    n: 3,
    name: 'Moon Gate',
    tagline: 'Through the blue gate, the town turns upside down.',
    difficulty: 'hard',
    stars: 5,
    bpm: 132,
    theme: 'moon',
    startMode: 'run',
    startSpeed: 'normal',
    modes: ['run', 'roll', 'kite'],
    sections: [
      {
        name: 'intro',
        bars: 4,
        energy: 1,
        mode: 'run',
        speed: 'normal',
        note: 'Moonlit and quiet.',
      },
      {
        name: 'a',
        bars: 8,
        energy: 2,
        mode: 'run',
        speed: 'normal',
        note: 'The blue gate: run upside down along the eaves; blue drums flip you back.',
      },
      {
        name: 'b',
        bars: 8,
        energy: 3,
        mode: 'roll',
        speed: 'normal',
        note: 'Roll: switch gravity between the roofs and the eaves.',
      },
      {
        name: 'c',
        bars: 8,
        energy: 3,
        mode: 'run',
        speed: 'normal',
        note: 'Blue and green lanterns flip you in mid-air.',
      },
      {
        name: 'd',
        bars: 8,
        energy: 4,
        mode: 'roll',
        speed: 'fast',
        note: 'Roll and Kite trade places, faster.',
      },
      {
        name: 'outro',
        bars: 4,
        energy: 1,
        mode: 'run',
        speed: 'normal',
        note: 'Home under the moon.',
      },
    ],
  },
  {
    id: 'storm-roofs',
    n: 4,
    name: 'Storm Roofs',
    tagline: 'Open the parasol. The storm is on the beat.',
    difficulty: 'harder',
    stars: 7,
    bpm: 140,
    theme: 'storm',
    startMode: 'run',
    startSpeed: 'normal',
    modes: ['run', 'parasol', 'kite'],
    sections: [
      {
        name: 'intro',
        bars: 4,
        energy: 2,
        mode: 'run',
        speed: 'normal',
        note: 'The rain starts.',
      },
      {
        name: 'a',
        bars: 8,
        energy: 3,
        mode: 'run',
        speed: 'normal',
        note: 'Swinging lanterns and steam vents that blow on the beat.',
      },
      {
        name: 'b',
        bars: 8,
        energy: 3,
        mode: 'parasol',
        speed: 'normal',
        note: 'Parasol through the storm.',
      },
      {
        name: 'c',
        bars: 8,
        energy: 4,
        mode: 'run',
        speed: 'fast',
        note: 'Fast: vents, gaps and lanterns.',
      },
      {
        name: 'd',
        bars: 12,
        energy: 5,
        mode: 'parasol',
        speed: 'faster',
        note: 'The storm breaks: Parasol and Kite at speed.',
      },
      {
        name: 'outro',
        bars: 4,
        energy: 2,
        mode: 'run',
        speed: 'normal',
        note: 'The rain eases.',
      },
    ],
  },
  {
    id: 'dragon-festival',
    n: 5,
    name: 'Dragon Festival',
    tagline: 'Ride the dragon, then step through the shadows.',
    difficulty: 'insane',
    stars: 9,
    bpm: 150,
    theme: 'sakura',
    startMode: 'run',
    startSpeed: 'normal',
    modes: ['run', 'dragon', 'shadow', 'roll'],
    sections: [
      {
        name: 'intro',
        bars: 4,
        energy: 2,
        mode: 'run',
        speed: 'normal',
        note: 'Fireworks over the festival.',
      },
      {
        name: 'a',
        bars: 8,
        energy: 3,
        mode: 'dragon',
        speed: 'normal',
        note: 'Dragon: zigzag through the lantern strings.',
      },
      {
        name: 'b',
        bars: 8,
        energy: 3,
        mode: 'shadow',
        speed: 'normal',
        note: 'Shadow Step between the roofs and the eaves.',
      },
      {
        name: 'c',
        bars: 8,
        energy: 4,
        mode: 'run',
        speed: 'fast',
        note: 'A fast run with lanterns and drums.',
      },
      {
        name: 'd',
        bars: 8,
        energy: 5,
        mode: 'dragon',
        speed: 'fast',
        note: 'Dragon, tighter and faster.',
      },
      {
        name: 'e',
        bars: 8,
        energy: 4,
        mode: 'shadow',
        speed: 'fast',
        note: 'Shadow Step and Roll together.',
      },
      {
        name: 'outro',
        bars: 4,
        energy: 2,
        mode: 'run',
        speed: 'normal',
        note: 'The parade passes.',
      },
    ],
  },
  {
    id: 'shadow-dojo',
    n: 6,
    name: 'Shadow Dojo',
    tagline: 'Every way to move, at the speed of a blade.',
    difficulty: 'demon',
    stars: 10,
    bpm: 160,
    theme: 'dojo',
    startMode: 'run',
    startSpeed: 'fast',
    modes: ['run', 'kite', 'dragon', 'shadow', 'roll', 'parasol'],
    sections: [
      {
        name: 'intro',
        bars: 4,
        energy: 3,
        mode: 'run',
        speed: 'fast',
        note: 'Ink and vermilion. No warm-up.',
      },
      {
        name: 'a',
        bars: 8,
        energy: 4,
        mode: 'run',
        speed: 'fast',
        note: 'A fast run: everything the first five levels taught.',
      },
      {
        name: 'b',
        bars: 8,
        energy: 4,
        mode: 'kite',
        speed: 'faster',
        note: 'Kite through spinning shuriken.',
      },
      {
        name: 'c',
        bars: 8,
        energy: 5,
        mode: 'dragon',
        speed: 'faster',
        note: 'Dragon at speed.',
      },
      {
        name: 'd',
        bars: 8,
        energy: 4,
        mode: 'shadow',
        speed: 'fast',
        note: 'Shadow Step and Roll.',
      },
      {
        name: 'e',
        bars: 8,
        energy: 5,
        mode: 'parasol',
        speed: 'faster',
        note: 'Parasol through the blades.',
      },
      {
        name: 'f',
        bars: 8,
        energy: 5,
        mode: 'run',
        speed: 'fastest',
        note: 'Everything, at the fastest speed.',
      },
      {
        name: 'outro',
        bars: 4,
        energy: 2,
        mode: 'run',
        speed: 'normal',
        note: 'Bow out.',
      },
    ],
  },
];

export function levelMeta(id: LevelId): LevelMeta {
  const m = LEVEL_METAS.find((l) => l.id === id);
  if (!m) throw new Error(`Unknown level ${id}`);
  return m;
}

/** Seconds of song a level is built to: bars × 4 beats at its tempo. */
export function levelSeconds(m: LevelMeta): number {
  const bars = m.sections.reduce((s, x) => s + x.bars, 0);
  return (bars * 4 * 60) / m.bpm;
}
