#!/usr/bin/env node
/**
 * Bakes the handful of Japanese characters the site draws into SVG path data,
 * so a page can paint a brush kanji without downloading a CJK font.
 *
 *   node scripts/build-glyphs.mjs
 *
 * Writes src/components/brand/glyphs.ts. Re-run it only when the character
 * list below changes — the output is committed.
 *
 * Why paths and not a font: a Japanese webfont is megabytes, and Google's
 * sliced version still costs a request per slice the page touches. The site
 * uses about thirty characters, all decorative, all known at build time. As
 * paths they cost a few hundred bytes each, render identically everywhere,
 * and can be stroked, masked and animated like any other SVG.
 *
 * Both faces are SIL Open Font License 1.1 (Google Fonts). The TTFs are
 * fetched into node_modules/.cache on first run and never committed.
 */
import { mkdirSync, existsSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import opentype from 'opentype.js';

const ROOT = process.cwd();
const CACHE = path.join(ROOT, 'node_modules/.cache/sd-glyphs');
const OUT = path.join(ROOT, 'src/components/brand/glyphs.ts');

const FACES = {
  // Brush calligraphy — the big watermark kanji on each page, and the seals.
  brush: {
    file: 'PottaOne-Regular.ttf',
    url: 'https://raw.githubusercontent.com/google/fonts/main/ofl/pottaone/PottaOne-Regular.ttf',
    chars: '忍書嵐創遊道秘消斬学速光影月桜侍技心新夢力風雷作探切る守岐',
  },
  // Heavy gothic — the vertical katakana tag. Same family as the display face.
  gothic: {
    file: 'DelaGothicOne-Regular.ttf',
    url: 'https://raw.githubusercontent.com/google/fonts/main/ofl/delagothicone/DelaGothicOne-Regular.ttf',
    chars: 'スマートディスラプションズ・忍',
  },
};

// Ideographic em box: CJK outlines sit in [-120, 880] font units on a 1000
// unit em, so a baseline at y=880 puts every glyph in a 0..1000 square.
const BASELINE = 880;

async function loadFace(face) {
  mkdirSync(CACHE, { recursive: true });
  const file = path.join(CACHE, face.file);
  if (!existsSync(file)) {
    const res = await fetch(face.url);
    if (!res.ok) throw new Error(`fetch ${face.url}: ${res.status}`);
    writeFileSync(file, Buffer.from(await res.arrayBuffer()));
  }
  return opentype.loadSync(file);
}

const round = (n) => Math.round(n);

function pathData(glyph, upm) {
  const scale = 1000 / upm;
  const p = glyph.getPath(0, BASELINE, 1000);
  // Integer font units are far below a visible pixel at any size we render.
  return p.commands
    .map((c) => {
      switch (c.type) {
        case 'M':
        case 'L':
          return `${c.type}${round(c.x)} ${round(c.y)}`;
        case 'Q':
          return `Q${round(c.x1)} ${round(c.y1)} ${round(c.x)} ${round(c.y)}`;
        case 'C':
          return `C${round(c.x1)} ${round(c.y1)} ${round(c.x2)} ${round(c.y2)} ${round(c.x)} ${round(c.y)}`;
        case 'Z':
          return 'Z';
        default:
          throw new Error(`unknown command ${c.type}`);
      }
    })
    .join('')
    .concat(scale === 1 ? '' : '');
}

const out = {};
for (const [name, face] of Object.entries(FACES)) {
  const font = await loadFace(face);
  out[name] = {};
  for (const ch of [...new Set(face.chars)]) {
    const glyph = font.charToGlyph(ch);
    if (!glyph || glyph.index === 0) throw new Error(`${face.file} has no glyph for ${ch}`);
    out[name][ch] = {
      d: pathData(glyph, font.unitsPerEm),
      w: round((glyph.advanceWidth * 1000) / font.unitsPerEm),
    };
  }
}

const body = `// GENERATED by scripts/build-glyphs.mjs — do not edit by hand.
// Outlines from Potta One (brush) and Dela Gothic One (gothic), SIL OFL 1.1.
// Each glyph sits in a 0..1000 square (ideographic em box); w is its advance.

export type GlyphFace = 'brush' | 'gothic';
export type Glyph = { d: string; w: number };

export const GLYPHS: Record<GlyphFace, Record<string, Glyph>> = ${JSON.stringify(out, null, 0)
  .replace(/\},"/g, '},\n  "')};
`;
writeFileSync(OUT, body);
const bytes = Buffer.byteLength(body);
console.log(`wrote ${path.relative(ROOT, OUT)} — ${Object.values(out).reduce((n, f) => n + Object.keys(f).length, 0)} glyphs, ${(bytes / 1024).toFixed(1)} KB`);
